
DROP DATABASE IF EXISTS JAVA_CRUD;
CREATE DATABASE JAVA_CRUD;
USE JAVA_CRUD;

CREATE TABLE PRODUCTS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    PRICE INT NOT NULL
);